numero_uno = int(input("Dime un numero: "))
numero_dos = int(input("Dime un numero: "))
numero_tres = int(input("Dime un numero: "))
mayor = int(max(numero_uno, numero_dos, numero_tres))
print(" ")
print("El numero más grande de los ingresados es {}".format(mayor))
